apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: et-ns
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: expense-tracker-app
  template:
    metadata:
      labels:
        app: expense-tracker-app
    spec:
      containers:
        - name: expense-tracker-container
          image: 188381035573.dkr.ecr.ap-south-1.amazonaws.com/expensetracker:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: et-configmap
                  key: MONGO_HOST
          