apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: et-ns
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30721
  selector:
    app:  expense-tracker-app
  type: NodePort