apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: et-ns
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: et-pvc
      containers:
        - name: mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db